### PR TITLE
Don't promote to `Matrix` with `PDMats` 1-arg constructor

### PR DESCRIPTION
**Pull request by chriselrod**
This should improve support for `StaticArrays`, for example.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Would be good to add a test for this and it should be fine to add StaticArrays as a test dependency.

**Comment by chriselrod** [comment]
I fixed `A::AbstractMatrix / B::PDiagMat`, but I'm not sure what to do about:
```julia
/(x::AbstractVector, a::PDiagMat) = a.inv_diag .* x
```
I'm not sure if this was intentional (probably should've been for `Adjoint`/`Transpose`, although that's covered by `AbstractMatrix`).
Removing it may be considered breaking?

**Comment by andreasnoack** [comment]
Hm. I think they are wrong. I've asked about it in https://github.com/JuliaStats/PDMats.jl/pull/105/files#r600569523. Is it necessary to reach those methods in the tests here?

**Comment by chriselrod** [comment]
I wanted to test a few basic uses (and test that they also return an `SMatrix`). I fixed the incorrect method being used in the tests.

**Comment by andreasnoack** [comment]
@chriselrod It would be great if you could resolve the conflicts here

**Pull request closed without merging**
