### PR TITLE
Sparse covariance matrices

### PR DESCRIPTION
**Pull request by scheidan**
A type and the required functions for sparse covariance matrices as mention in #23. However, I need some help with two points:
-  It passes the `test_pdmat` test, however, not the addition tests.  Should the addition methods be derived automatically or do we have to add the new methods in `addition.jl` manually?

- I'm not sure if all calculations in `pdsparsemat.jl` are done in the most efficient way.

### CODE REVIEW

**Comment by lindahua** [comment]
In terms of add, you may at least add a method that implements addition between this type of matrix and ``PDMat``.

**Comment by scheidan** [comment]
Added the addition between the other `PDMats` types. 

Maybe we should update the `README.md` as it currently implies that the addition methods are derived automatically for a new `AbstractPDMat` subtypes.

I'll investigate why it fails with the nightly build.

**Comment by scheidan** [comment]
works now with Julia 0.3 and the latest nightly

**Comment by lindahua** [comment]
Thanks! Looks great.

**Pull request merged**
